# Generated by Django 3.0.7 on 2020-06-17 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=20)),
                ('buId', models.CharField(max_length=20)),
                ('casaCampaignId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenantId', models.CharField(max_length=20)),
                ('buId', models.CharField(max_length=20)),
                ('casaCustomerId', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='', max_length=2000)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaSuggestApp.Campaign')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaSuggestApp.Customer')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CasaSuggestApp.Message')),
            ],
        ),
    ]
